import { TagViewModel } from 'src/app/autogenerated/catalog/models';

export class TagDto implements TagViewModel {
  public name: string = '';
  public id: string = '';

  public constructor(dto?: TagViewModel) {
    if (dto) {
      this.name = dto.name;
      this.id = dto.id;
    }
  }
}
