import { Tag } from "src/app/autogenerated/catalog/models";

export class TagDto implements Tag {
  public name: string = "";
  public id: string = "";

  public constructor(dto?: Tag) {
    if (dto) {
      this.name = dto.name;
      this.id = dto.id;
    }
  }
}
